<?php

namespace Demv\Werte\Vorsorge;

enum BiproVersicherungssummeOderLeistungBasis: string
{
    case GARANTIERTE_ABLAUFLEISTUNG                    = 'GarantierteAblaufleistung';
    case GESAMTE_ABLAUFLEISTUNG                        = 'GesamteAblaufleistung';
    case GARANTIERTE_RENTE                             = 'GarantierteRente';
    case GESAMTE_RENTE                                 = 'GesamteRente';
    case GARANTIERTE_TODESFALLLEISTUNG                 = 'GarantierteTodesfallleistung';
    case GESAMTE_TODESFALLLEISTUNG                     = 'GesamteTodesfallleistung';
    case KH_DECKUNGSSUMME_PERSONENSCHADEN              = 'KHDeckungssummePersonenschaden';
    case KH_DECKUNGSSUMME_SACHSCHADEN                  = 'KHDeckungssummeSachschaden';
    case KH_DECKUNGSSUMME_VERMOEGENSSCHADEN            = 'KHDeckungssummeVermoegensschaden';
    case KU_VERSICHERUNGSSUMME_TOD                     = 'KUVersicherungssummeTod';
    case KU_VERSICHERUNGSSUMME_INVALIDITAET            = 'KUVersicherungssummeInvaliditaet';
    case KU_VERSICHERUNGSSUMME_TAGEGELD                = 'KUVersicherungssummeTagegeld';
    case KU_VERSICHERUNGSSUMME_KRANKENHAUSTAGEGELD     = 'KUVersicherungssummeKrankenhaustagegeld';
    case KU_VERSICHERUNGSSUMME_ANZAHL_PLAETZE          = 'KUVersicherungssummeAnzahlPlaetze';
    case DECKUNGSSUMME_PERSONENSCHADEN                 = 'DeckungssummePersonenschaden';
    case DECKUNGSSUMME_SACHSCHADEN                     = 'DeckungssummeSachschaden';
    case DECKUNGSSUMME_VERMOEGENSSCHADEN               = 'DeckungssummeVermoegensschaden';
    case DECKUNGSSUMME_PERSONEN_SACHSCHADEN            = 'DeckungssummePersonenSachschaden';
    case DECKUNGSSUMME_SACH_VERMOEGENSSCHADEN          = 'DeckungssummeSachVermoegensschaden';
    case DECKUNGSSUMME_PERSONEN_SACH_VERMOEGENSSCHADEN = 'DeckungssummePersonenSachVermoegensschaden';
    case VERSICHERUNGSSUMME                            = 'Versicherungssumme';
    case HOECHSTENTSCHAEDIGUNGSSUMME                   = 'Hoechstentschaedigungssumme';
    case VERSICHERUNGSSUMME_GLEITENDER_NEUWERT         = 'VersicherungssummeGleitenderNeuwert';
    case VERSICHERUNGSSUMME_NEUWERT                    = 'VersicherungssummeNeuwert';
    case VERSICHERUNGSSUMME_ZEITWERT                   = 'VersicherungssummeZeitwert';
    case PROGRESSION                                   = 'Progression';
    case LEISTUNG_AB_INVALIDITAETSGRAD                 = 'LeistungAbInvaliditaetsgrad';
    case RENTENZAHLUNG_BIS_ALTER                       = 'RentenzahlungBisAlter';
    case EINMALIGE_LEISTUNG_BEI_VOLLINVALIDITAET       = 'EinmaligeLeistungBeiVollinvaliditaet';
    case KRANKENTAGEGELD_NACH_AMBULANTER_OP            = 'KrankentagegeldNachAmbulanterOP';
    case LEISTUNG_AB_TAG                               = 'LeistungAbTag';
    case KRANKENHAUSTAGEGELD_MIT_GENESUNGSGELD         = 'KrankenhaustagegeldMitGenesungsgeld';
    case BLINDENMONATSRENTE                            = 'Blindenmonatsrente';
    case ERWEITERTE_GLIEDERTAXE                        = 'ErweiterteGliedertaxe';
    case KRANKENTAGEGELD                               = 'Krankentagegeld';
    case KRANKENHAUSTAGEGELD                           = 'Krankenhaustagegeld';
    case PFLEGETAGEGELD                                = 'Pflegetagegeld';
    case PFLEGETAGEGELD_AMBULANT                       = 'PflegetagegeldAmbulant';
    case PFLEGETAGEGELD_STATIONAER                     = 'PflegetagegeldStationaer';
    case KURTAGEGELD                                   = 'Kurtagegeld';
    case GARANTIERTE_PFLEGERENTE_STUFE_0               = 'GarantiertePflegerenteStufe0';
    case GARANTIERTE_PFLEGERENTE_STUFE_1               = 'GarantiertePflegerenteStufe1';
    case GARANTIERTE_PFLEGERENTE_STUFE_2               = 'GarantiertePflegerenteStufe2';
    case GARANTIERTE_PFLEGERENTE_STUFE_3               = 'GarantiertePflegerenteStufe3';
    case GESAMTE_PFLEGERENTE_STUFE_0                   = 'GesamtePflegerenteStufe0';
    case GESAMTE_PFLEGERENTE_STUFE_1                   = 'GesamtePflegerenteStufe1';
    case GESAMTE_PFLEGERENTE_STUFE_2                   = 'GesamtePflegerenteStufe2';
    case GESAMTE_PFLEGERENTE_STUFE_3                   = 'GesamtePflegerenteStufe3';
    case SOFORTLEISTUNG                                = 'Sofortleistung';
    case WERKSTATTBINDUNG                              = 'Werkstattbindung';
    case VERSICHERUNGSSUMME_PRO_QM                     = 'VersicherungssummeProQm';
    case KU_VERSICHERUNGSSUMME_HEILKOSTEN              = 'KUVersicherungssummeHeilkosten';
    case KU_ANZAHL_PLAETZE                             = 'KUAnzahlPlaetze';
    case KU_KTG_MIT_GENESUNGSGELD                      = 'KUKtgMitGenesungsgeld';
    case VERSICHERUNGSSUMME_AKTUELL                    = 'VersicherungssummeAktuell';
    case BEITRAGSRUECKERSTATTUNG                       = 'Beitragsrueckerstattung';
    case PFLEGEKOSTEN                                  = 'Pflegekosten';
    case BEITRAGSENTLASTUNG_ANSPARPHASE                = 'BeitragsentlastungAnsparphase';
    case BEITRAGSENTLASTUNG_LEISTUNGSPHASE             = 'BeitragsentlastungLeistungsphase';
    case POLICENDARLEHEN                               = 'Policendarlehen';
    case RISIKOVORLAUF                                 = 'Risikovorlauf';
    case WITWEN_ODER_WITWERRENTE                       = 'WitwenOderWitwerrente';
    case WAISENRENTE                                   = 'Waisenrente';
    case GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_1          = 'GarantiertePflegerentePflegegrad1';
    case GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_2          = 'GarantiertePflegerentePflegegrad2';
    case GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_3          = 'GarantiertePflegerentePflegegrad3';
    case GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_4          = 'GarantiertePflegerentePflegegrad4';
    case GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_5          = 'GarantiertePflegerentePflegegrad5';
    case GESAMTE_PFLEGERENTE_PFLEGEGRAD_1              = 'GesamtePflegerentePflegegrad1';
    case GESAMTE_PFLEGERENTE_PFLEGEGRAD_2              = 'GesamtePflegerentePflegegrad2';
    case GESAMTE_PFLEGERENTE_PFLEGEGRAD_3              = 'GesamtePflegerentePflegegrad3';
    case GESAMTE_PFLEGERENTE_PFLEGEGRAD_4              = 'GesamtePflegerentePflegegrad4';
    case GESAMTE_PFLEGERENTE_PFLEGEGRAD_5              = 'GesamtePflegerentePflegegrad5';
    case GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_1   = 'GarantierteEinmaligeLeistungPflegegrad1';
    case GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_2   = 'GarantierteEinmaligeLeistungPflegegrad2';
    case GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_3   = 'GarantierteEinmaligeLeistungPflegegrad3';
    case GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_4   = 'GarantierteEinmaligeLeistungPflegegrad4';
    case GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_5   = 'GarantierteEinmaligeLeistungPflegegrad5';
    case GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_1       = 'GesamteEinmaligeLeistungPflegegrad1';
    case GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_2       = 'GesamteEinmaligeLeistungPflegegrad2';
    case GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_3       = 'GesamteEinmaligeLeistungPflegegrad3';
    case GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_4       = 'GesamteEinmaligeLeistungPflegegrad4';
    case GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_5       = 'GesamteEinmaligeLeistungPflegegrad5';
    case ZUGETEILTE_UEBERSCHUESSE_ABLAUFLEISTUNG       = 'ZugeteilteUeberschuesseAblaufleistung';
    case ZUGETEILTE_UEBERSCHUESSE_RENTE                = 'ZugeteilteUeberschuesseRente';
    case ZUGETEILTE_UEBERSCHUESSE_TODESFALLLEISTUNG    = 'ZugeteilteUeberschuesseTodesfallleistung';
    case GARANTIERTE_HINTERBLIEBENENRENTE              = 'GarantierteHinterbliebenenrente';
    case GESAMTE_HINTERBLIEBENENRENTE                  = 'GesamteHinterbliebenenrente';

    public function getLabel(): string
    {
        return match ($this) {
            self::GARANTIERTE_ABLAUFLEISTUNG                    => 'Garantierte Ablaufleistung',
            self::GESAMTE_ABLAUFLEISTUNG                        => 'Gesamte Ablaufleistung',
            self::GARANTIERTE_RENTE                             => 'Garantierte Rente',
            self::GESAMTE_RENTE                                 => 'Gesamte Rente',
            self::GARANTIERTE_TODESFALLLEISTUNG                 => 'Garantierte Todesfallleistung',
            self::GESAMTE_TODESFALLLEISTUNG                     => 'Gesamte Todesfallleistung',
            self::KH_DECKUNGSSUMME_PERSONENSCHADEN              => 'KH Deckungssumme Personenschaden',
            self::KH_DECKUNGSSUMME_SACHSCHADEN                  => 'KH Deckungssumme Sachschaden',
            self::KH_DECKUNGSSUMME_VERMOEGENSSCHADEN            => 'KH Deckungssumme Vermögensschaden',
            self::KU_VERSICHERUNGSSUMME_TOD                     => 'KU Versicherungssumme Tod',
            self::KU_VERSICHERUNGSSUMME_INVALIDITAET            => 'KU Versicherungssumme Invalidität',
            self::KU_VERSICHERUNGSSUMME_TAGEGELD                => 'KU Versicherungssumme Tagegeld',
            self::KU_VERSICHERUNGSSUMME_KRANKENHAUSTAGEGELD     => 'KU Versicherungssumme Krankenhaustagegeld',
            self::KU_VERSICHERUNGSSUMME_ANZAHL_PLAETZE          => 'KU Versicherungssumme Anzahl Plätze',
            self::DECKUNGSSUMME_PERSONENSCHADEN                 => 'Deckungssumme Personenschaden',
            self::DECKUNGSSUMME_SACHSCHADEN                     => 'Deckungssumme Sachschaden',
            self::DECKUNGSSUMME_VERMOEGENSSCHADEN               => 'Deckungssumme Vermögensschaden',
            self::DECKUNGSSUMME_PERSONEN_SACHSCHADEN            => 'Deckungssumme Personen- und Sachschaden',
            self::DECKUNGSSUMME_SACH_VERMOEGENSSCHADEN          => 'Deckungssumme Sach- und Vermögensschaden',
            self::DECKUNGSSUMME_PERSONEN_SACH_VERMOEGENSSCHADEN => 'Deckungssumme Personen-, Sach- und Vermögensschaden',
            self::VERSICHERUNGSSUMME                            => 'Versicherungssumme',
            self::HOECHSTENTSCHAEDIGUNGSSUMME                   => 'Höchstentschädigungssumme',
            self::VERSICHERUNGSSUMME_GLEITENDER_NEUWERT         => 'Versicherungssumme Gleitender Neuwert',
            self::VERSICHERUNGSSUMME_NEUWERT                    => 'Versicherungssumme Neuwert',
            self::VERSICHERUNGSSUMME_ZEITWERT                   => 'Versicherungssumme Zeitwert',
            self::PROGRESSION                                   => 'Progression',
            self::LEISTUNG_AB_INVALIDITAETSGRAD                 => 'Leistung ab Invaliditätsgrad',
            self::RENTENZAHLUNG_BIS_ALTER                       => 'Rentenzahlung bis Alter',
            self::EINMALIGE_LEISTUNG_BEI_VOLLINVALIDITAET       => 'Einmalige Leistung bei Vollinvalidität',
            self::KRANKENTAGEGELD_NACH_AMBULANTER_OP            => 'Krankentagegeld nach ambulanter OP',
            self::LEISTUNG_AB_TAG                               => 'Leistung ab Tag',
            self::KRANKENHAUSTAGEGELD_MIT_GENESUNGSGELD         => 'Krankenhaustagegeld mit Genesungsgeld',
            self::BLINDENMONATSRENTE                            => 'Blindenmonatsrente',
            self::ERWEITERTE_GLIEDERTAXE                        => 'Erweiterte Gliedertaxe',
            self::KRANKENTAGEGELD                               => 'Krankentagegeld',
            self::KRANKENHAUSTAGEGELD                           => 'Krankenhaustagegeld',
            self::PFLEGETAGEGELD                                => 'Pflegetagegeld',
            self::PFLEGETAGEGELD_AMBULANT                       => 'Pflegetagegeld ambulant',
            self::PFLEGETAGEGELD_STATIONAER                     => 'Pflegetagegeld stationär',
            self::KURTAGEGELD                                   => 'Kurtagegeld',
            self::GARANTIERTE_PFLEGERENTE_STUFE_0               => 'Garantierte Pflegerente Stufe 0',
            self::GARANTIERTE_PFLEGERENTE_STUFE_1               => 'Garantierte Pflegerente Stufe I',
            self::GARANTIERTE_PFLEGERENTE_STUFE_2               => 'Garantierte Pflegerente Stufe II',
            self::GARANTIERTE_PFLEGERENTE_STUFE_3               => 'Garantierte Pflegerente Stufe III',
            self::GESAMTE_PFLEGERENTE_STUFE_0                   => 'Gesamte Pflegerente Stufe 0',
            self::GESAMTE_PFLEGERENTE_STUFE_1                   => 'Gesamte Pflegerente Stufe I',
            self::GESAMTE_PFLEGERENTE_STUFE_2                   => 'Gesamte Pflegerente Stufe II',
            self::GESAMTE_PFLEGERENTE_STUFE_3                   => 'Gesamte Pflegerente Stufe III',
            self::SOFORTLEISTUNG                                => 'Sofortleistung',
            self::WERKSTATTBINDUNG                              => 'Werkstattbindung',
            self::VERSICHERUNGSSUMME_PRO_QM                     => 'Versicherungssumme pro qm',
            self::KU_VERSICHERUNGSSUMME_HEILKOSTEN              => 'KU Versicherungssumme Heilkosten',
            self::KU_ANZAHL_PLAETZE                             => 'KU Anzahl Plätze',
            self::KU_KTG_MIT_GENESUNGSGELD                      => 'KU KTG mit Genesungsgeld',
            self::VERSICHERUNGSSUMME_AKTUELL                    => 'Versicherungssumme aktuell',
            self::BEITRAGSRUECKERSTATTUNG                       => 'Beitragsrückerstattung',
            self::PFLEGEKOSTEN                                  => 'Pflegekosten',
            self::BEITRAGSENTLASTUNG_ANSPARPHASE                => 'Beitragsentlastung Ansparphase',
            self::BEITRAGSENTLASTUNG_LEISTUNGSPHASE             => 'Beitragsentlastung Leistungsphase',
            self::POLICENDARLEHEN                               => 'Policendarlehen',
            self::RISIKOVORLAUF                                 => 'Risikovorlauf',
            self::WITWEN_ODER_WITWERRENTE                       => 'Witwen- oder Witwerrente',
            self::WAISENRENTE                                   => 'Waisenrente',
            self::GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_1          => 'Garantierte Pflegerente Pflegegrad 1',
            self::GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_2          => 'Garantierte Pflegerente Pflegegrad 2',
            self::GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_3          => 'Garantierte Pflegerente Pflegegrad 3',
            self::GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_4          => 'Garantierte Pflegerente Pflegegrad 4',
            self::GARANTIERTE_PFLEGERENTE_PFLEGEGRAD_5          => 'Garantierte Pflegerente Pflegegrad 5',
            self::GESAMTE_PFLEGERENTE_PFLEGEGRAD_1              => 'Gesamte Pflegerente Pflegegrad 1',
            self::GESAMTE_PFLEGERENTE_PFLEGEGRAD_2              => 'Gesamte Pflegerente Pflegegrad 2',
            self::GESAMTE_PFLEGERENTE_PFLEGEGRAD_3              => 'Gesamte Pflegerente Pflegegrad 3',
            self::GESAMTE_PFLEGERENTE_PFLEGEGRAD_4              => 'Gesamte Pflegerente Pflegegrad 4',
            self::GESAMTE_PFLEGERENTE_PFLEGEGRAD_5              => 'Gesamte Pflegerente Pflegegrad 5',
            self::GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_1   => 'Garantierte einmalige Leistung Pflegegrad 1',
            self::GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_2   => 'Garantierte einmalige Leistung Pflegegrad 2',
            self::GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_3   => 'Garantierte einmalige Leistung Pflegegrad 3',
            self::GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_4   => 'Garantierte einmalige Leistung Pflegegrad 4',
            self::GARANTIERTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_5   => 'Garantierte einmalige Leistung Pflegegrad 5',
            self::GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_1       => 'Gesamte einmalige Leistung Pflegegrad 1',
            self::GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_2       => 'Gesamte einmalige Leistung Pflegegrad 2',
            self::GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_3       => 'Gesamte einmalige Leistung Pflegegrad 3',
            self::GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_4       => 'Gesamte einmalige Leistung Pflegegrad 4',
            self::GESAMTE_EINMALIGE_LEISTUNG_PFLEGEGRAD_5       => 'Gesamte einmalige Leistung Pflegegrad 5',
            self::ZUGETEILTE_UEBERSCHUESSE_ABLAUFLEISTUNG       => 'Zugeteilte Überschüsse Ablaufleistung',
            self::ZUGETEILTE_UEBERSCHUESSE_RENTE                => 'Zugeteilte Überschüsse Rente',
            self::ZUGETEILTE_UEBERSCHUESSE_TODESFALLLEISTUNG    => 'Zugeteilte Überschüsse Todesfallleistung',
            self::GARANTIERTE_HINTERBLIEBENENRENTE              => 'Garantierte Hinterbliebenenrente',
            self::GESAMTE_HINTERBLIEBENENRENTE                  => 'Gesamte Hinterbliebenenrente',
        };
    }
}
