language: php
php:
  - 7.1
  - 7.2
  - nightly
before_install:
   - if [[ $TRAVIS_PHP_VERSION != "nightly" ]]; then phpenv config-rm xdebug.ini; fi
install:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader
script:
  - composer test
cache:
  directories:
    - $HOME/.composer/cache/files
