FROM php:8.5-cli@sha256:8d55a195c072c3d390956bd3f1d64752a8cf56433da149f4c217bd7471b25546

ARG GITHUB_TOKEN

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer  --2
RUN composer config -g github-oauth.github.com $GITHUB_TOKEN

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git


#install some base extensions
RUN apt-get install -y \
        libzip-dev \
        zip \
  && docker-php-ext-install zip
WORKDIR /var/www/html
