FROM php:7.4-cli@sha256:620a6b9f4d4feef2210026172570465e9d0c1de79766418d3affd09190a7fda5

ARG GITHUB_TOKEN

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --2
RUN composer config -g github-oauth.github.com $GITHUB_TOKEN

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git


#install some base extensions
RUN apt-get install -y \
        libzip-dev \
        zip \
  && docker-php-ext-install zip
WORKDIR /var/www/html
