<?php

/**
 * Created by PhpStorm.
 * User: alex
 * Date: 06.01.17
 * Time: 11:14
 */
namespace Demv\Werte\Person\Anrede;

use Demv\Werte\AbstractProvider;

final class Anreden extends AbstractProvider
{
    const HERR  = 1;
    const FRAU  = 2;
    const FIRMA = 3;
    const LEER  = 4;

    public function __construct()
    {
        $this->appendMember(new Anrede(self::HERR, 'Herr'));
        $this->appendMember(new Anrede(self::FRAU, 'Frau'));
        $this->appendMember(new Anrede(self::FIRMA, 'Firma'));
        $this->appendMember(new Anrede(self::LEER, ''));
    }

    /**
     * @return Anrede[]
     */
    public function getAll(): array
    {
        return parent::getAll(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function getOne($id): Anrede
    {
        return parent::getOne($id); // TODO: Change the autogenerated stub
    }

}