<?php

namespace Demv\Werte\Vertragsdetails\KFZ;

enum Herstellername: int
{
    case ACCESS_MOTOR                   = 1;
    case ACHILLES                       = 2;
    case ADLER                          = 3;
    case AEON                           = 4;
    case AEON_MOTOR                     = 5;
    case AGRATI                         = 6;
    case AIXAM                          = 7;
    case ALFA_ROMEO                     = 8;
    case ALPINE                         = 9;
    case AMSTRONG                       = 10;
    case APRILIA                        = 11;
    case ARDIE                          = 12;
    case ARKUS_ROMET                    = 13;
    case AUDI_AG                        = 14;
    case AUSA_E                         = 15;
    case AUTO_UNION                     = 16;
    case AUTOBIANCHI                    = 17;
    case AUTOCYCLE_TECHCENTER           = 18;
    case AUTOMOBILWERK_EISENACH         = 19;
    case AZLK_MOSKAU                    = 20;
    case BAJAJ_AUTO                     = 21;
    case BARKAS                         = 22;
    case BAROSSA_MOTOR                  = 23;
    case BASTERT                        = 24;
    case BAUER                          = 25;
    case BELGARDA                       = 26;
    case BENELLI                        = 27;
    case BETAMOTOR                      = 28;
    case BIMOTA                         = 29;
    case BISMARCK                       = 30;
    case BLUECAR                        = 31;
    case BMW                            = 32;
    case BOEHM_MOT                      = 33;
    case BOMBARDIER                     = 34;
    case BORGWARD                       = 35;
    case BOSS_HOSS                      = 36;
    case BOXER                          = 37;
    case BUECKER                        = 38;
    case BUELL                          = 39;
    case BYD                            = 40;
    case C_P_I_MOTOR                    = 41;
    case CAGIVA                         = 42;
    case CAPS                           = 43;
    case CEMOTO                         = 44;
    case CHANGZHOU                      = 45;
    case CHANGZHOU_KWANG                = 46;
    case CHINA_ENGINE                   = 47;
    case CHONGQING_CHANGAN_RC           = 48;
    case CHONGQING_DONGBEN              = 49;
    case CHONGQING_HUANSONG             = 50;
    case CHONGQING_JIANSHE              = 51;
    case CHONGQING_LIANFEI              = 52;
    case CHONGQING_LIFAN                = 53;
    case CHONGQING_LONCIN               = 54;
    case CHONGQING_SHINERAY             = 55;
    case CHONGQING_YINXIANG             = 56;
    case CHRYSLER                       = 57;
    case CHRYSLER_USA                   = 58;
    case CHUN_LAN                       = 59;
    case CHUNFENG                       = 60;
    case CIMATTI                        = 61;
    case CITROEN                        = 62;
    case CIXI                           = 63;
    case CZM                            = 64;
    case DACIA_PITESTI                  = 65;
    case DAELIM                         = 66;
    case DAEWOO                         = 67;
    case DAIHATSU                       = 68;
    case DEMHARTER                      = 69;
    case DINLI                          = 70;
    case DONGFENG                       = 71;
    case DS_AUTOMOBILES                 = 72;
    case DUCATI                         = 73;
    case DUERKOPP                       = 74;
    case E_ATV_RACING                   = 75;
    case E_GO_MOBILE_AG                 = 76;
    case EGIMOTORS                      = 77;
    case ENFIELD                        = 78;
    case EXPRESS                        = 79;
    case FAHRZ_SUHL                     = 80;
    case FAKA                           = 81;
    case FANTIC_MOTOR                   = 82;
    case FERRARI                        = 83;
    case FIAT                           = 84;
    case FORD_EUROPA                    = 85;
    case FORD_USA                       = 86;
    case FOTON_LOVOL                    = 87;
    case FUJI_HEAVY_SUBARU              = 88;
    case GAMAX                          = 89;
    case GAS_GAS_MOTOS                  = 90;
    case GEIER                          = 91;
    case GENERAL_MOTORS                 = 92;
    case GLAS                           = 93;
    case GLIDER                         = 94;
    case GM_KOREA                       = 95;
    case GMC                            = 96;
    case GOERICKE                       = 97;
    case GORGOLIS                       = 98;
    case GREAT_WALL_MOTOR               = 99;
    case GRITZ_KAYS                     = 100;
    case GRUETER_GUT                    = 101;
    case GUANGDONG_TAYO                 = 102;
    case GUANGZHOU_FEKON                = 103;
    case GUANGZHOU_HAOJIN               = 104;
    case GUANGZHOU_PA_HUANAN            = 105;
    case HANOMAG                        = 106;
    case HANWAY                         = 107;
    case HAOJIAN                        = 108;
    case HARLEY_DAVIDSON                = 109;
    case HARTFORD                       = 110;
    case HECKER                         = 111;
    case HEIDEMANN                      = 112;
    case HEINKEL                        = 113;
    case HER_CHEE                       = 114;
    case HERCULES                       = 115;
    case HOFFMANN                       = 116;
    case HONDA                          = 117;
    case HONDA_MOTOR                    = 118;
    case HOREX                          = 119;
    case HRD                            = 120;
    case HUABAO                         = 121;
    case HUSABERG                       = 122;
    case HUSQVARNA                      = 123;
    case HYOSUNG                        = 124;
    case HYUNDAI                        = 125;
    case INDIAN_MOTORCYCLE              = 126;
    case INEOS                          = 127;
    case INNOCENTI                      = 128;
    case INTREPRINDEREA                 = 129;
    case IRBIT                          = 130;
    case ISUZU                          = 131;
    case ITALIAN_MOTORCYCLE             = 132;
    case ITALJET                        = 133;
    case IVECO                          = 134;
    case JAGUAR                         = 135;
    case JAWA                           = 136;
    case JEEP                           = 137;
    case JENSEN                         = 138;
    case JET_POWER                      = 139;
    case JIANG_DA_CHANGJIANG            = 140;
    case JIANGM_GIANTCO                 = 141;
    case JIANGMEN_DA_CHANG              = 142;
    case JIANGMEN_HUARI                 = 143;
    case JIANGSU_DAFIER                 = 144;
    case JIANGSU_LINHAI                 = 145;
    case JIANGSU_SACIN                  = 146;
    case JIANGSU_SINSKI_SONIK           = 147;
    case JINAN_QINGQI                   = 148;
    case JOCHEN_SOMMER                  = 149;
    case JORDAN_MOTORS                  = 150;
    case K_L                            = 151;
    case KANUNI                         = 152;
    case KAWASAKI                       = 153;
    case KEEN                           = 154;
    case KIA                            = 155;
    case KIA_MOTOR                      = 156;
    case KIA_MOTORS                     = 157;
    case KR_MOTORS                      = 158;
    case KREIDLER                       = 159;
    case KREIDLER_EUROPE                = 160;
    case KSR                            = 161;
    case KTM                            = 162;
    case KUBA_MOTOR                     = 163;
    case KUNSTSTOFF                     = 164;
    case KWANG_YANG                     = 165;
    case KYBURZ                         = 166;
    case L_M_P                          = 167;
    case LADA                           = 168;
    case LAMBORGHINI                    = 169;
    case LAMBRETTA                      = 170;
    case LANCIA                         = 171;
    case LAND_ROVER                     = 172;
    case LANDWIND                       = 173;
    case LDV                            = 174;
    case LENNARTSFORS                   = 175;
    case LEVC                           = 176;
    case LEXUS                          = 177;
    case LIFAN                          = 178;
    case LIGIER                         = 179;
    case LLOYD                          = 180;
    case LML_LIMITED                    = 181;
    case LONCIN_GROUP                   = 182;
    case LORYC                          = 183;
    case MAICO                          = 184;
    case MALAGUTI                       = 185;
    case MALTRITZ                       = 186;
    case MANURHIN                       = 187;
    case MARS                           = 188;
    case MASERATI                       = 189;
    case MATRA                          = 190;
    case MAZDA                          = 191;
    case MAZDA_MOTOR                    = 192;
    case MBK                            = 193;
    case MEISTER                        = 194;
    case MELKUS                         = 195;
    case MERCEDES_BENZ_AG               = 196;
    case MIA_ELECTRIC                   = 197;
    case MIELE                          = 198;
    case MITSUBISHI                     = 199;
    case MO_LAVERDA                     = 200;
    case MONTESA                        = 201;
    case MORGAN                         = 202;
    case MOTO_BM                        = 203;
    case MOTO_MORINI                    = 204;
    case MOTO_GUZZI                     = 205;
    case MOTOBECA                       = 206;
    case MOTORHISP                      = 207;
    case MUZ                            = 208;
    case MV_AGUSTA                      = 209;
    case MZ                             = 210;
    case NACIONAL                       = 211;
    case NACIONAL_MOTOR                 = 212;
    case NEMAUSUS                       = 213;
    case NEW_REBEL                      = 214;
    case NEXT_E_GO_MOBILE               = 215;
    case NINGBO_LONGJIA                 = 216;
    case NIO_RC                         = 217;
    case NIPPONIA                       = 218;
    case NISSAN                         = 219;
    case NSU                            = 220;
    case OPEL                           = 221;
    case OPEN_CONCEPTS                  = 222;
    case PAMAG                          = 223;
    case PANTHER                        = 224;
    case PATRIA                         = 225;
    case PELPI                          = 226;
    case PERAVES                        = 227;
    case PEUGEOT                        = 228;
    case PHAENOMEN                      = 229;
    case PIAGGIO                        = 230;
    case POLARIS                        = 231;
    case POLESTAR                       = 232;
    case PORSCHE                        = 233;
    case POVA_JAWA                      = 234;
    case PROGRESS                       = 235;
    case PROTON                         = 236;
    case PSA_AUTOMOBILES                = 237;
    case QINGQI                         = 238;
    case QUADRO                         = 239;
    case QUADRO_TECNOLOGIE              = 240;
    case R_G_P                          = 241;
    case RABENEICK                      = 242;
    case REINMECH_CORP                  = 243;
    case RENAULT                        = 244;
    case REWACO                         = 245;
    case RIEDEL                         = 246;
    case RIEJU                          = 247;
    case RIXE                           = 248;
    case ROEHR                          = 249;
    case ROVER                          = 250;
    case S_T_MOTORS                     = 251;
    case SAAB                           = 252;
    case SACHS                          = 253;
    case SACHSENRINGWERK                = 254;
    case SAIC                           = 255;
    case SANYANG                        = 256;
    case SCCM                           = 257;
    case SCOMADI                        = 258;
    case SEAT                           = 259;
    case SFM                            = 260;
    case SHANDONG_ASIAWING              = 261;
    case SHANGHAI_JMSTAR                = 262;
    case SHANGHAI_SHENKE                = 263;
    case SHE_RC                         = 264;
    case SHERCO                         = 265;
    case SI_ZWEIRAD                     = 266;
    case SIAM                           = 267;
    case SIMSON                         = 268;
    case SKODA                          = 269;
    case SKY_TEAM                       = 270;
    case SMART                          = 271;
    case SPEEDBRAIN                     = 272;
    case SSANGYONG                      = 273;
    case STANDARD_M                     = 274;
    case STANDARD_MOTOR                 = 275;
    case STARTRIKE                      = 276;
    case STEYR_PUCH                     = 277;
    case SUBARU                         = 278;
    case SUHL                           = 279;
    case SUNDIRO_HONDA                  = 280;
    case SUZUKI                         = 281;
    case SWM                            = 282;
    case TAIW_GOLDEN_BEE                = 283;
    case TAIZHOU_CHUANL                 = 284;
    case TAIZHOU_WANGYE                 = 285;
    case TAIZHOU_ZHONGNENG              = 286;
    case TALBOT                         = 287;
    case TATA                           = 288;
    case TAZZARI                        = 289;
    case TEAM_AZZALIN_I                 = 290;
    case TECDRIVE                       = 291;
    case TESLA                          = 292;
    case TOMBERLIN                      = 293;
    case TORNAX                         = 294;
    case TORPEDO                        = 295;
    case TORROT                         = 296;
    case TOYOTA                         = 297;
    case TREMOLA                        = 298;
    case TRIKETEC                       = 299;
    case TRIUMPH                        = 300;
    case UGUR_MOTORLU                   = 301;
    case UM_LOHIA                       = 302;
    case UNILLI_MOTOR                   = 303;
    case UT                             = 304;
    case VAUXHALL                       = 305;
    case VENUS                          = 306;
    case VERTEMATI                      = 307;
    case VESPA                          = 308;
    case VICTORIA                       = 309;
    case VINFAST                        = 310;
    case VOLKSWAGEN                     = 311;
    case VOLVO                          = 312;
    case VOR_MOTORI                     = 313;
    case VOXAN                          = 314;
    case WK_TRIKES                      = 315;
    case WOLGA                          = 316;
    case WOLGA_AUTOWERK_VAZ             = 317;
    case WUHAN_LOTUS                    = 318;
    case WUYANG_HONDA                   = 319;
    case XIAMEN_XIASHING                = 320;
    case XINGYUE                        = 321;
    case YAMAHA                         = 322;
    case YONGKANG_CHANGSHUN             = 323;
    case ZASTAVA                        = 324;
    case ZHAOQING_XIAOPENG_RC           = 325;
    case ZHEJIANG_CFMOTO                = 326;
    case ZHEJIANG_CHANGLING             = 327;
    case ZHEJIANG_GEELY                 = 328;
    case ZHEJIANG_JIAJIAJUNENG          = 329;
    case ZHEJIANG_JIAJUE                = 330;
    case ZHEJIANG_JINLI                 = 331;
    case ZHEJIANG_JMSTAR_SHEN           = 332;
    case ZHEJIANG_JMSTAR_SHENKE         = 333;
    case ZHEJIANG_JONWAY                = 334;
    case ZHEJIANG_LINGYU                = 335;
    case ZHEJIANG_QIANJIANG             = 336;
    case ZHEJIANG_RENLI                 = 337;
    case ZHEJIANG_SHANQI                = 338;
    case ZHEJIANG_SHENMAO               = 339;
    case ZHEJIANG_WANGYE                = 340;
    case ZHEJIANG_XINGYUE               = 341;
    case ZHEJIANG_YONGJIANG             = 342;
    case ZHEJIANG_ZHONGNAN              = 343;
    case ZHUZH_JIANSHE_YAMAHA           = 344;
    case ZUENDAPP                       = 345;
    case ZWEIRAD_UN                     = 346;

    public function getLabel(): string
    {
        return match ($this) {
            self::ACCESS_MOTOR                   => 'Access Motor',
            self::ACHILLES                       => 'ACHILLES',
            self::ADLER                          => 'ADLER',
            self::AEON                           => 'AEON',
            self::AEON_MOTOR                     => 'AEON MOTOR',
            self::AGRATI                         => 'AGRATI',
            self::AIXAM                          => 'AIXAM',
            self::ALFA_ROMEO                     => 'ALFA ROMEO',
            self::ALPINE                         => 'ALPINE',
            self::AMSTRONG                       => 'AMSTRONG',
            self::APRILIA                        => 'APRILIA',
            self::ARDIE                          => 'ARDIE',
            self::ARKUS_ROMET                    => 'Arkus&Romet',
            self::AUDI_AG                        => 'AUDI AG',
            self::AUSA_E                         => 'AUSA (E)',
            self::AUTO_UNION                     => 'AUTO UNION',
            self::AUTOBIANCHI                    => 'AUTOBIANCHI',
            self::AUTOCYCLE_TECHCENTER           => 'autocycle techcenter',
            self::AUTOMOBILWERK_EISENACH         => 'AUTOMOBILWERK EISENACH',
            self::AZLK_MOSKAU                    => 'AZLK MOSKAU',
            self::BAJAJ_AUTO                     => 'BAJAJ AUTO',
            self::BARKAS                         => 'BARKAS',
            self::BAROSSA_MOTOR                  => 'BAROSSA MOTOR',
            self::BASTERT                        => 'BASTERT',
            self::BAUER                          => 'BAUER',
            self::BELGARDA                       => 'BELGARDA',
            self::BENELLI                        => 'BENELLI',
            self::BETAMOTOR                      => 'BETAMOTOR',
            self::BIMOTA                         => 'BIMOTA',
            self::BISMARCK                       => 'BISMARCK',
            self::BLUECAR                        => 'BLUECAR',
            self::BMW                            => 'BMW',
            self::BOEHM_MOT                      => 'BOEHM-MOT',
            self::BOMBARDIER                     => 'BOMBARDIER',
            self::BORGWARD                       => 'BORGWARD',
            self::BOSS_HOSS                      => 'BOSS HOSS',
            self::BOXER                          => 'BOXER',
            self::BUECKER                        => 'BUECKER',
            self::BUELL                          => 'BUELL',
            self::BYD                            => 'BYD',
            self::C_P_I_MOTOR                    => 'C.P.I. MOTOR',
            self::CAGIVA                         => 'CAGIVA',
            self::CAPS                           => 'CAPS',
            self::CEMOTO                         => 'CEMOTO',
            self::CHANGZHOU                      => 'CHANGZHOU',
            self::CHANGZHOU_KWANG                => 'CHANGZHOU KWANG.',
            self::CHINA_ENGINE                   => 'China Engine',
            self::CHONGQING_CHANGAN_RC           => 'CHONGQING CHANGAN (RC)',
            self::CHONGQING_DONGBEN              => 'Chongqing Dongben',
            self::CHONGQING_HUANSONG             => 'CHONGQING HUANSONG',
            self::CHONGQING_JIANSHE              => 'Chongqing Jianshe',
            self::CHONGQING_LIANFEI              => 'Chongqing Lianfei',
            self::CHONGQING_LIFAN                => 'Chongqing Lifan',
            self::CHONGQING_LONCIN               => 'CHONGQING LONCIN',
            self::CHONGQING_SHINERAY             => 'Chongqing SHINERAY',
            self::CHONGQING_YINXIANG             => 'ChongQing YinXiang',
            self::CHRYSLER                       => 'CHRYSLER',
            self::CHRYSLER_USA                   => 'CHRYSLER (USA)',
            self::CHUN_LAN                       => 'CHUN LAN',
            self::CHUNFENG                       => 'Chunfeng',
            self::CIMATTI                        => 'CIMATTI',
            self::CITROEN                        => 'CITROEN',
            self::CIXI                           => 'CIXI',
            self::CZM                            => 'CZM',
            self::DACIA_PITESTI                  => 'DACIA PITESTI',
            self::DAELIM                         => 'DAELIM',
            self::DAEWOO                         => 'DAEWOO',
            self::DAIHATSU                       => 'DAIHATSU',
            self::DEMHARTER                      => 'Demharter',
            self::DINLI                          => 'DINLI',
            self::DONGFENG                       => 'DONGFENG',
            self::DS_AUTOMOBILES                 => 'DS Automobiles',
            self::DUCATI                         => 'DUCATI',
            self::DUERKOPP                       => 'DUERKOPP',
            self::E_ATV_RACING                   => 'E.-ATV RACING',
            self::E_GO_MOBILE_AG                 => 'E.GO MOBILE AG',
            self::EGIMOTORS                      => 'EGIMOTORS',
            self::ENFIELD                        => 'ENFIELD',
            self::EXPRESS                        => 'EXPRESS',
            self::FAHRZ_SUHL                     => 'FAHRZ-SUHL',
            self::FAKA                           => 'FAKA',
            self::FANTIC_MOTOR                   => 'FANTIC MOTOR',
            self::FERRARI                        => 'FERRARI',
            self::FIAT                           => 'FIAT',
            self::FORD_EUROPA                    => 'FORD/EUROPA',
            self::FORD_USA                       => 'FORD/USA',
            self::FOTON_LOVOL                    => 'Foton Lovol',
            self::FUJI_HEAVY_SUBARU              => 'FUJI HEAVY/SUBARU',
            self::GAMAX                          => 'Gamax',
            self::GAS_GAS_MOTOS                  => 'GAS GAS MOTOS',
            self::GEIER                          => 'GEIER',
            self::GENERAL_MOTORS                 => 'GENERAL MOTORS',
            self::GLAS                           => 'GLAS',
            self::GLIDER                         => 'GLIDER',
            self::GM_KOREA                       => 'GM Korea',
            self::GMC                            => 'GMC',
            self::GOERICKE                       => 'GOERICKE',
            self::GORGOLIS                       => 'GORGOLIS',
            self::GREAT_WALL_MOTOR               => 'GREAT WALL MOTOR',
            self::GRITZ_KAYS                     => 'GRITZ-KAYS',
            self::GRUETER_GUT                    => 'GRUETER+GUT',
            self::GUANGDONG_TAYO                 => 'Guangdong Tayo',
            self::GUANGZHOU_FEKON                => 'GUANGZHOU FEKON',
            self::GUANGZHOU_HAOJIN               => 'Guangzhou Haojin',
            self::GUANGZHOU_PA_HUANAN            => 'Guangzhou Pa.Huanan',
            self::HANOMAG                        => 'HANOMAG',
            self::HANWAY                         => 'HANWAY',
            self::HAOJIAN                        => 'Haojian',
            self::HARLEY_DAVIDSON                => 'HARLEY-DAVIDSON',
            self::HARTFORD                       => 'HARTFORD',
            self::HECKER                         => 'HECKER',
            self::HEIDEMANN                      => 'HEIDEMANN',
            self::HEINKEL                        => 'HEINKEL',
            self::HER_CHEE                       => 'HER CHEE',
            self::HERCULES                       => 'HERCULES',
            self::HOFFMANN                       => 'HOFFMANN',
            self::HONDA                          => 'HONDA',
            self::HONDA_MOTOR                    => 'HONDA MOTOR',
            self::HOREX                          => 'HOREX',
            self::HRD                            => 'HRD',
            self::HUABAO                         => 'Huabao',
            self::HUSABERG                       => 'HUSABERG',
            self::HUSQVARNA                      => 'HUSQVARNA',
            self::HYOSUNG                        => 'HYOSUNG',
            self::HYUNDAI                        => 'HYUNDAI',
            self::INDIAN_MOTORCYCLE              => 'Indian Motorcycle',
            self::INEOS                          => 'INEOS',
            self::INNOCENTI                      => 'INNOCENTI',
            self::INTREPRINDEREA                 => 'INTREPRINDEREA',
            self::IRBIT                          => 'IRBIT',
            self::ISUZU                          => 'ISUZU',
            self::ITALIAN_MOTORCYCLE             => 'Italian Motorcycle',
            self::ITALJET                        => 'ITALJET',
            self::IVECO                          => 'IVECO',
            self::JAGUAR                         => 'JAGUAR',
            self::JAWA                           => 'JAWA',
            self::JEEP                           => 'JEEP',
            self::JENSEN                         => 'Jensen',
            self::JET_POWER                      => 'Jet Power',
            self::JIANG_DA_CHANGJIANG            => 'Jiang.Da Changjiang',
            self::JIANGM_GIANTCO                 => 'JIANGM.GIANTCO',
            self::JIANGMEN_DA_CHANG              => 'Jiangmen Da Chang',
            self::JIANGMEN_HUARI                 => 'JIANGMEN HUARI',
            self::JIANGSU_DAFIER                 => 'Jiangsu Dafier',
            self::JIANGSU_LINHAI                 => 'JIANGSU LINHAI',
            self::JIANGSU_SACIN                  => 'JIANGSU SACIN',
            self::JIANGSU_SINSKI_SONIK           => 'JIANGSU SINSKI SONIK',
            self::JINAN_QINGQI                   => 'Jinan Qingqi',
            self::JOCHEN_SOMMER                  => 'JOCHEN SOMMER',
            self::JORDAN_MOTORS                  => 'JORDAN MOTORS',
            self::K_L                            => 'K.L.',
            self::KANUNI                         => 'KANUNI',
            self::KAWASAKI                       => 'KAWASAKI',
            self::KEEN                           => 'KEEN',
            self::KIA                            => 'KIA',
            self::KIA_MOTOR                      => 'KIA MOTOR',
            self::KIA_MOTORS                     => 'KIA MOTORS',
            self::KR_MOTORS                      => 'KR Motors',
            self::KREIDLER                       => 'KREIDLER',
            self::KREIDLER_EUROPE                => 'Kreidler Europe',
            self::KSR                            => 'KSR',
            self::KTM                            => 'KTM',
            self::KUBA_MOTOR                     => 'KUBA MOTOR',
            self::KUNSTSTOFF                     => 'KUNSTSTOFF',
            self::KWANG_YANG                     => 'KWANG YANG',
            self::KYBURZ                         => 'Kyburz',
            self::L_M_P                          => 'L.M.P.',
            self::LADA                           => 'LADA',
            self::LAMBORGHINI                    => 'LAMBORGHINI',
            self::LAMBRETTA                      => 'Lambretta',
            self::LANCIA                         => 'LANCIA',
            self::LAND_ROVER                     => 'Land Rover',
            self::LANDWIND                       => 'LANDWIND',
            self::LDV                            => 'LDV',
            self::LENNARTSFORS                   => 'Lennartsfors',
            self::LEVC                           => 'LEVC',
            self::LEXUS                          => 'LEXUS',
            self::LIFAN                          => 'Lifan',
            self::LIGIER                         => 'LIGIER',
            self::LLOYD                          => 'LLOYD',
            self::LML_LIMITED                    => 'LML Limited',
            self::LONCIN_GROUP                   => 'LONCIN GROUP',
            self::LORYC                          => 'LORYC',
            self::MAICO                          => 'MAICO',
            self::MALAGUTI                       => 'MALAGUTI',
            self::MALTRITZ                       => 'MALTRITZ',
            self::MANURHIN                       => 'MANURHIN',
            self::MARS                           => 'MARS',
            self::MASERATI                       => 'MASERATI',
            self::MATRA                          => 'MATRA',
            self::MAZDA                          => 'Mazda',
            self::MAZDA_MOTOR                    => 'MAZDA MOTOR',
            self::MBK                            => 'MBK',
            self::MEISTER                        => 'MEISTER',
            self::MELKUS                         => 'MELKUS',
            self::MERCEDES_BENZ_AG               => 'MERCEDES-BENZ AG',
            self::MIA_ELECTRIC                   => 'MIA ELECTRIC',
            self::MIELE                          => 'MIELE',
            self::MITSUBISHI                     => 'MITSUBISHI',
            self::MO_LAVERDA                     => 'MO.LAVERDA',
            self::MONTESA                        => 'MONTESA',
            self::MORGAN                         => 'MORGAN',
            self::MOTO_BM                        => 'MOTO BM',
            self::MOTO_MORINI                    => 'MOTO MORINI',
            self::MOTO_GUZZI                     => 'MOTO-GUZZI',
            self::MOTOBECA                       => 'MOTOBECA',
            self::MOTORHISP                      => 'MOTORHISP.',
            self::MUZ                            => 'MUZ',
            self::MV_AGUSTA                      => 'MV AGUSTA',
            self::MZ                             => 'MZ',
            self::NACIONAL                       => 'NACIONAL',
            self::NACIONAL_MOTOR                 => 'NACIONAL MOTOR',
            self::NEMAUSUS                       => 'NEMAUSUS',
            self::NEW_REBEL                      => 'New Rebel',
            self::NEXT_E_GO_MOBILE               => 'NEXT.E.GO MOBILE',
            self::NINGBO_LONGJIA                 => 'Ningbo Longjia',
            self::NIO_RC                         => 'NIO (RC)',
            self::NIPPONIA                       => 'NIPPONIA',
            self::NISSAN                         => 'NISSAN',
            self::NSU                            => 'NSU',
            self::OPEL                           => 'OPEL',
            self::OPEN_CONCEPTS                  => 'OPEN CONCEPTS',
            self::PAMAG                          => 'PAMAG',
            self::PANTHER                        => 'PANTHER',
            self::PATRIA                         => 'PATRIA',
            self::PELPI                          => 'PELPI',
            self::PERAVES                        => 'PERAVES',
            self::PEUGEOT                        => 'PEUGEOT',
            self::PHAENOMEN                      => 'PHAENOMEN',
            self::PIAGGIO                        => 'PIAGGIO',
            self::POLARIS                        => 'POLARIS',
            self::POLESTAR                       => 'POLESTAR',
            self::PORSCHE                        => 'PORSCHE',
            self::POVA_JAWA                      => 'POVA-JAWA',
            self::PROGRESS                       => 'PROGRESS',
            self::PROTON                         => 'PROTON',
            self::PSA_AUTOMOBILES                => 'PSA AUTOMOBILES',
            self::QINGQI                         => 'Qingqi',
            self::QUADRO                         => 'QUADRO',
            self::QUADRO_TECNOLOGIE              => 'QUADRO TECNOLOGIE',
            self::R_G_P                          => 'R.G.P.',
            self::RABENEICK                      => 'RABENEICK',
            self::REINMECH_CORP                  => 'REINMECH CORP.',
            self::RENAULT                        => 'RENAULT',
            self::REWACO                         => 'REWACO',
            self::RIEDEL                         => 'RIEDEL',
            self::RIEJU                          => 'RIEJU',
            self::RIXE                           => 'RIXE',
            self::ROEHR                          => 'ROEHR',
            self::ROVER                          => 'ROVER',
            self::S_T_MOTORS                     => 'S&T Motors',
            self::SAAB                           => 'SAAB',
            self::SACHS                          => 'SACHS',
            self::SACHSENRINGWERK                => 'SACHSENRINGWERK',
            self::SAIC                           => 'SAIC',
            self::SANYANG                        => 'SANYANG',
            self::SCCM                           => 'SCCM',
            self::SCOMADI                        => 'Scomadi',
            self::SEAT                           => 'SEAT',
            self::SFM                            => 'SFM',
            self::SHANDONG_ASIAWING              => 'SHANDONG ASIAWING',
            self::SHANGHAI_JMSTAR                => 'Shanghai Jmstar',
            self::SHANGHAI_SHENKE                => 'Shanghai Shenke',
            self::SHE_RC                         => 'SHE/RC',
            self::SHERCO                         => 'SHERCO',
            self::SI_ZWEIRAD                     => 'SI-Zweirad',
            self::SIAM                           => 'SIAM',
            self::SIMSON                         => 'SIMSON',
            self::SKODA                          => 'SKODA',
            self::SKY_TEAM                       => 'SKY TEAM',
            self::SMART                          => 'SMART',
            self::SPEEDBRAIN                     => 'Speedbrain',
            self::SSANGYONG                      => 'SSANGYONG',
            self::STANDARD_M                     => 'STANDARD M',
            self::STANDARD_MOTOR                 => 'STANDARD MOTOR',
            self::STARTRIKE                      => 'STARTRIKE',
            self::STEYR_PUCH                     => 'STEYR-PUCH',
            self::SUBARU                         => 'SUBARU',
            self::SUHL                           => 'SUHL',
            self::SUNDIRO_HONDA                  => 'Sundiro Honda',
            self::SUZUKI                         => 'SUZUKI',
            self::SWM                            => 'SWM',
            self::TAIW_GOLDEN_BEE                => 'TAIW.GOLDEN BEE',
            self::TAIZHOU_CHUANL                 => 'Taizhou Chuanl',
            self::TAIZHOU_WANGYE                 => 'Taizhou Wangye',
            self::TAIZHOU_ZHONGNENG              => 'Taizhou Zhongneng',
            self::TALBOT                         => 'TALBOT',
            self::TATA                           => 'TATA',
            self::TAZZARI                        => 'TAZZARI',
            self::TEAM_AZZALIN_I                 => 'TEAM AZZALIN (I)',
            self::TECDRIVE                       => 'TECDRIVE',
            self::TESLA                          => 'TESLA',
            self::TOMBERLIN                      => 'Tomberlin',
            self::TORNAX                         => 'TORNAX',
            self::TORPEDO                        => 'TORPEDO',
            self::TORROT                         => 'TORROT',
            self::TOYOTA                         => 'TOYOTA',
            self::TREMOLA                        => 'Tremola',
            self::TRIKETEC                       => 'TRIKETEC',
            self::TRIUMPH                        => 'TRIUMPH',
            self::UGUR_MOTORLU                   => 'UGUR MOTORLU',
            self::UM_LOHIA                       => 'UM Lohia',
            self::UNILLI_MOTOR                   => 'UNILLI MOTOR',
            self::UT                             => 'UT',
            self::VAUXHALL                       => 'VAUXHALL',
            self::VENUS                          => 'VENUS',
            self::VERTEMATI                      => 'VERTEMATI',
            self::VESPA                          => 'VESPA',
            self::VICTORIA                       => 'VICTORIA',
            self::VINFAST                        => 'VINFAST',
            self::VOLKSWAGEN                     => 'VOLKSWAGEN',
            self::VOLVO                          => 'VOLVO',
            self::VOR_MOTORI                     => 'VOR MOTORI',
            self::VOXAN                          => 'VOXAN',
            self::WK_TRIKES                      => 'WK TRIKES',
            self::WOLGA                          => 'WOLGA',
            self::WOLGA_AUTOWERK_VAZ             => 'WOLGA-AUTOWERK VAZ',
            self::WUHAN_LOTUS                    => 'WUHAN LOTUS',
            self::WUYANG_HONDA                   => 'Wuyang-Honda',
            self::XIAMEN_XIASHING                => 'Xiamen Xiashing',
            self::XINGYUE                        => 'Xingyue',
            self::YAMAHA                         => 'YAMAHA',
            self::YONGKANG_CHANGSHUN             => 'Yongkang Changshun',
            self::ZASTAVA                        => 'ZASTAVA',
            self::ZHAOQING_XIAOPENG_RC           => 'ZHAOQING XIAOPENG (RC)',
            self::ZHEJIANG_CFMOTO                => 'ZHEJIANG CFMOTO',
            self::ZHEJIANG_CHANGLING             => 'Zhejiang Changling',
            self::ZHEJIANG_GEELY                 => 'ZHEJIANG GEELY',
            self::ZHEJIANG_JIAJIAJUNENG          => 'Zhejiang JiajiaJuneng',
            self::ZHEJIANG_JIAJUE                => 'Zhejiang Jiajue',
            self::ZHEJIANG_JINLI                 => 'Zhejiang Jinli',
            self::ZHEJIANG_JMSTAR_SHEN           => 'Zhejiang Jmstar Shen.',
            self::ZHEJIANG_JMSTAR_SHENKE         => 'Zhejiang Jmstar Shenke',
            self::ZHEJIANG_JONWAY                => 'Zhejiang Jonway',
            self::ZHEJIANG_LINGYU                => 'Zhejiang Lingyu',
            self::ZHEJIANG_QIANJIANG             => 'Zhejiang QianJiang',
            self::ZHEJIANG_RENLI                 => 'Zhejiang Renli',
            self::ZHEJIANG_SHANQI                => 'Zhejiang Shanqi',
            self::ZHEJIANG_SHENMAO               => 'Zhejiang Shenmao',
            self::ZHEJIANG_WANGYE                => 'Zhejiang Wangye',
            self::ZHEJIANG_XINGYUE               => 'Zhejiang XingYue',
            self::ZHEJIANG_YONGJIANG             => 'Zhejiang Yongjiang',
            self::ZHEJIANG_ZHONGNAN              => 'Zhejiang Zhongnan',
            self::ZHUZH_JIANSHE_YAMAHA           => 'Zhuzh.Jianshe Yamaha',
            self::ZUENDAPP                       => 'ZUENDAPP',
            self::ZWEIRAD_UN                     => 'ZWEIRAD-UN',
        };
    }
}
