<?php

namespace Demv\Werte\Vertragsdetails\Allgemein;

enum Waehrungsschluessel: int
{
    case XXX = 999;
    case USN = 997;
    case XSU = 994;
    case CLF = 990;
    case BRL = 986;
    case PLN = 985;
    case BOV = 984;
    case GEL = 981;
    case UAH = 980;
    case MXV = 979;
    case EUR = 978;
    case BAM = 977;
    case CDF = 976;
    case BGN = 975;
    case AOA = 973;
    case TJS = 972;
    case AFN = 971;
    case COU = 970;
    case MGA = 969;
    case SRD = 968;
    case ZMW = 967;
    case XUA = 965;
    case XPD = 964;
    case XTS = 963;
    case XPT = 962;
    case XAG = 961;
    case XDR = 960;
    case XAU = 959;
    case XBD = 958;
    case XBC = 957;
    case XBB = 956;
    case XBA = 955;
    case XPF = 953;
    case XOF = 952;
    case XCD = 951;
    case XAF = 950;
    case TRY = 949;
    case CHW = 948;
    case CHE = 947;
    case RON = 946;
    case AZN = 944;
    case MZN = 943;
    case RSD = 941;
    case UYI = 940;
    case SDG = 938;
    case GHS = 936;
    case TMT = 934;
    case BYN = 933;
    case STN = 930;
    case MRU = 929;
    case VES = 928;
    case UYW = 927;
    case VED = 926;
    case SLE = 925;
    case ZWG = 924;
    case TWD = 901;
    case YER = 886;
    case WST = 882;
    case UZS = 860;
    case UYU = 858;
    case USD = 840;
    case TZS = 834;
    case GBP = 826;
    case EGP = 818;
    case MKD = 807;
    case UGX = 800;
    case TND = 788;
    case AED = 784;
    case TTD = 780;
    case TOP = 776;
    case THB = 764;
    case SYP = 760;
    case CHF = 756;
    case SEK = 752;
    case SZL = 748;
    case SSP = 728;
    case ZAR = 710;
    case SOS = 706;
    case VND = 704;
    case SGD = 702;
    case SCR = 690;
    case SAR = 682;
    case SHP = 654;
    case RWF = 646;
    case RUB = 643;
    case QAR = 634;
    case PHP = 608;
    case PEN = 604;
    case PYG = 600;
    case PGK = 598;
    case PAB = 590;
    case PKR = 586;
    case NOK = 578;
    case NGN = 566;
    case NIO = 558;
    case NZD = 554;
    case VUV = 548;
    case AWG = 533;
    case XCG = 532;
    case NPR = 524;
    case NAD = 516;
    case OMR = 512;
    case MAD = 504;
    case MDL = 498;
    case MNT = 496;
    case MXN = 484;
    case MUR = 480;
    case MVR = 462;
    case MYR = 458;
    case MWK = 454;
    case MOP = 446;
    case LYD = 434;
    case LRD = 430;
    case LSL = 426;
    case LBP = 422;
    case LAK = 418;
    case KGS = 417;
    case KWD = 414;
    case KRW = 410;
    case KPW = 408;
    case KES = 404;
    case JOD = 400;
    case KZT = 398;
    case XAD = 396;
    case JPY = 392;
    case JMD = 388;
    case ILS = 376;
    case IQD = 368;
    case IRR = 364;
    case IDR = 360;
    case INR = 356;
    case ISK = 352;
    case HUF = 348;
    case HKD = 344;
    case HNL = 340;
    case HTG = 332;
    case GYD = 328;
    case GNF = 324;
    case GTQ = 320;
    case GIP = 292;
    case GMD = 270;
    case DJF = 262;
    case FJD = 242;
    case FKP = 238;
    case ERN = 232;
    case ETB = 230;
    case SVC = 222;
    case DOP = 214;
    case DKK = 208;
    case CZK = 203;
    case CUP = 192;
    case CRC = 188;
    case KMF = 174;
    case COP = 170;
    case CNY = 156;
    case CLP = 152;
    case LKR = 144;
    case KYD = 136;
    case CVE = 132;
    case CAD = 124;
    case KHR = 116;
    case BIF = 108;
    case MMK = 104;
    case BND = 96;
    case SBD = 90;
    case BZD = 84;
    case BWP = 72;
    case BOB = 68;
    case BTN = 64;
    case BMD = 60;
    case BBD = 52;
    case AMD = 51;
    case BDT = 50;
    case BHD = 48;
    case BSD = 44;
    case AUD = 36;
    case ARS = 32;
    case DZD = 12;
    case ALL = 8;

    public function getLabel(): string
    {
        return match ($this) {
            self::XXX => 'The codes assigned for transactions where no currency is involved',
            self::USN => 'US Dollar (Next day)',
            self::XSU => 'Sucre',
            self::CLF => 'Unidad de Fomento',
            self::BRL => 'Brazilian Real',
            self::PLN => 'Zloty',
            self::BOV => 'Mvdol',
            self::GEL => 'Lari',
            self::UAH => 'Hryvnia',
            self::MXV => 'Mexican Unidad de Inversion (UDI)',
            self::EUR => 'Euro',
            self::BAM => 'Convertible Mark',
            self::CDF => 'Congolese Franc',
            self::BGN => 'Bulgarian Lev',
            self::AOA => 'Kwanza',
            self::TJS => 'Somoni',
            self::AFN => 'Afghani',
            self::COU => 'Unidad de Valor Real',
            self::MGA => 'Malagasy Ariary',
            self::SRD => 'Surinam Dollar',
            self::ZMW => 'Zambian Kwacha',
            self::XUA => 'ADB Unit of Account',
            self::XPD => 'Palladium',
            self::XTS => 'Codes specifically reserved for testing purposes',
            self::XPT => 'Platinum',
            self::XAG => 'Silver',
            self::XDR => 'SDR (Special Drawing Right)',
            self::XAU => 'Gold',
            self::XBD => 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
            self::XBC => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
            self::XBB => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
            self::XBA => 'Bond Markets Unit European Composite Unit (EURCO)',
            self::XPF => 'CFP Franc',
            self::XOF => 'CFA Franc BCEAO',
            self::XCD => 'East Caribbean Dollar',
            self::XAF => 'CFA Franc BEAC',
            self::TRY => 'Turkish Lira',
            self::CHW => 'WIR Franc',
            self::CHE => 'WIR Euro',
            self::RON => 'Romanian Leu',
            self::AZN => 'Azerbaijan Manat',
            self::MZN => 'Mozambique Metical',
            self::RSD => 'Serbian Dinar',
            self::UYI => 'Uruguay Peso en Unidades Indexadas (UI)',
            self::SDG => 'Sudanese Pound',
            self::GHS => 'Ghana Cedi',
            self::TMT => 'Turkmenistan New Manat',
            self::BYN => 'Belarusian Ruble',
            self::STN => 'Dobra',
            self::MRU => 'Ouguiya',
            self::VES => 'Bolívar Soberano',
            self::UYW => 'Unidad Previsional',
            self::VED => 'Bolívar Soberano',
            self::SLE => 'Leone',
            self::ZWG => 'Zimbabwe Gold',
            self::TWD => 'New Taiwan Dollar',
            self::YER => 'Yemeni Rial',
            self::WST => 'Tala',
            self::UZS => 'Uzbekistan Sum',
            self::UYU => 'Peso Uruguayo',
            self::USD => 'US Dollar',
            self::TZS => 'Tanzanian Shilling',
            self::GBP => 'Pound Sterling',
            self::EGP => 'Egyptian Pound',
            self::MKD => 'Denar',
            self::UGX => 'Uganda Shilling',
            self::TND => 'Tunisian Dinar',
            self::AED => 'UAE Dirham',
            self::TTD => 'Trinidad and Tobago Dollar',
            self::TOP => 'Pa’anga',
            self::THB => 'Baht',
            self::SYP => 'Syrian Pound',
            self::CHF => 'Swiss Franc',
            self::SEK => 'Swedish Krona',
            self::SZL => 'Lilangeni',
            self::SSP => 'South Sudanese Pound',
            self::ZAR => 'Rand',
            self::SOS => 'Somali Shilling',
            self::VND => 'Dong',
            self::SGD => 'Singapore Dollar',
            self::SCR => 'Seychelles Rupee',
            self::SAR => 'Saudi Riyal',
            self::SHP => 'Saint Helena Pound',
            self::RWF => 'Rwanda Franc',
            self::RUB => 'Russian Ruble',
            self::QAR => 'Qatari Rial',
            self::PHP => 'Philippine Peso',
            self::PEN => 'Sol',
            self::PYG => 'Guarani',
            self::PGK => 'Kina',
            self::PAB => 'Balboa',
            self::PKR => 'Pakistan Rupee',
            self::NOK => 'Norwegian Krone',
            self::NGN => 'Naira',
            self::NIO => 'Cordoba Oro',
            self::NZD => 'New Zealand Dollar',
            self::VUV => 'Vatu',
            self::AWG => 'Aruban Florin',
            self::XCG => 'Caribbean Guilder',
            self::NPR => 'Nepalese Rupee',
            self::NAD => 'Namibia Dollar',
            self::OMR => 'Rial Omani',
            self::MAD => 'Moroccan Dirham',
            self::MDL => 'Moldovan Leu',
            self::MNT => 'Tugrik',
            self::MXN => 'Mexican Peso',
            self::MUR => 'Mauritius Rupee',
            self::MVR => 'Rufiyaa',
            self::MYR => 'Malaysian Ringgit',
            self::MWK => 'Malawi Kwacha',
            self::MOP => 'Pataca',
            self::LYD => 'Libyan Dinar',
            self::LRD => 'Liberian Dollar',
            self::LSL => 'Loti',
            self::LBP => 'Lebanese Pound',
            self::LAK => 'Lao Kip',
            self::KGS => 'Som',
            self::KWD => 'Kuwaiti Dinar',
            self::KRW => 'Won',
            self::KPW => 'North Korean Won',
            self::KES => 'Kenyan Shilling',
            self::JOD => 'Jordanian Dinar',
            self::KZT => 'Tenge',
            self::XAD => 'Arab Accounting Dinar',
            self::JPY => 'Yen',
            self::JMD => 'Jamaican Dollar',
            self::ILS => 'New Israeli Sheqel',
            self::IQD => 'Iraqi Dinar',
            self::IRR => 'Iranian Rial',
            self::IDR => 'Rupiah',
            self::INR => 'Indian Rupee',
            self::ISK => 'Iceland Krona',
            self::HUF => 'Forint',
            self::HKD => 'Hong Kong Dollar',
            self::HNL => 'Lempira',
            self::HTG => 'Gourde',
            self::GYD => 'Guyana Dollar',
            self::GNF => 'Guinean Franc',
            self::GTQ => 'Quetzal',
            self::GIP => 'Gibraltar Pound',
            self::GMD => 'Dalasi',
            self::DJF => 'Djibouti Franc',
            self::FJD => 'Fiji Dollar',
            self::FKP => 'Falkland Islands Pound',
            self::ERN => 'Nakfa',
            self::ETB => 'Ethiopian Birr',
            self::SVC => 'El Salvador Colon',
            self::DOP => 'Dominican Peso',
            self::DKK => 'Danish Krone',
            self::CZK => 'Czech Koruna',
            self::CUP => 'Cuban Peso',
            self::CRC => 'Costa Rican Colon',
            self::KMF => 'Comorian Franc ',
            self::COP => 'Colombian Peso',
            self::CNY => 'Yuan Renminbi',
            self::CLP => 'Chilean Peso',
            self::LKR => 'Sri Lanka Rupee',
            self::KYD => 'Cayman Islands Dollar',
            self::CVE => 'Cabo Verde Escudo',
            self::CAD => 'Canadian Dollar',
            self::KHR => 'Riel',
            self::BIF => 'Burundi Franc',
            self::MMK => 'Kyat',
            self::BND => 'Brunei Dollar',
            self::SBD => 'Solomon Islands Dollar',
            self::BZD => 'Belize Dollar',
            self::BWP => 'Pula',
            self::BOB => 'Boliviano',
            self::BTN => 'Ngultrum',
            self::BMD => 'Bermudian Dollar',
            self::BBD => 'Barbados Dollar',
            self::AMD => 'Armenian Dram',
            self::BDT => 'Taka',
            self::BHD => 'Bahraini Dinar',
            self::BSD => 'Bahamian Dollar',
            self::AUD => 'Australian Dollar',
            self::ARS => 'Argentine Peso',
            self::DZD => 'Algerian Dinar',
            self::ALL => 'Lek',
        };
    }

    public function getAlphabeticCode(): string
    {
        return match ($this) {
            self::XXX => 'XXX',
            self::USN => 'USN',
            self::XSU => 'XSU',
            self::CLF => 'CLF',
            self::BRL => 'BRL',
            self::PLN => 'PLN',
            self::BOV => 'BOV',
            self::GEL => 'GEL',
            self::UAH => 'UAH',
            self::MXV => 'MXV',
            self::EUR => 'EUR',
            self::BAM => 'BAM',
            self::CDF => 'CDF',
            self::BGN => 'BGN',
            self::AOA => 'AOA',
            self::TJS => 'TJS',
            self::AFN => 'AFN',
            self::COU => 'COU',
            self::MGA => 'MGA',
            self::SRD => 'SRD',
            self::ZMW => 'ZMW',
            self::XUA => 'XUA',
            self::XPD => 'XPD',
            self::XTS => 'XTS',
            self::XPT => 'XPT',
            self::XAG => 'XAG',
            self::XDR => 'XDR',
            self::XAU => 'XAU',
            self::XBD => 'XBD',
            self::XBC => 'XBC',
            self::XBB => 'XBB',
            self::XBA => 'XBA',
            self::XPF => 'XPF',
            self::XOF => 'XOF',
            self::XCD => 'XCD',
            self::XAF => 'XAF',
            self::TRY => 'TRY',
            self::CHW => 'CHW',
            self::CHE => 'CHE',
            self::RON => 'RON',
            self::AZN => 'AZN',
            self::MZN => 'MZN',
            self::RSD => 'RSD',
            self::UYI => 'UYI',
            self::SDG => 'SDG',
            self::GHS => 'GHS',
            self::TMT => 'TMT',
            self::BYN => 'BYN',
            self::STN => 'STN',
            self::MRU => 'MRU',
            self::VES => 'VES',
            self::UYW => 'UYW',
            self::VED => 'VED',
            self::SLE => 'SLE',
            self::ZWG => 'ZWG',
            self::TWD => 'TWD',
            self::YER => 'YER',
            self::WST => 'WST',
            self::UZS => 'UZS',
            self::UYU => 'UYU',
            self::USD => 'USD',
            self::TZS => 'TZS',
            self::GBP => 'GBP',
            self::EGP => 'EGP',
            self::MKD => 'MKD',
            self::UGX => 'UGX',
            self::TND => 'TND',
            self::AED => 'AED',
            self::TTD => 'TTD',
            self::TOP => 'TOP',
            self::THB => 'THB',
            self::SYP => 'SYP',
            self::CHF => 'CHF',
            self::SEK => 'SEK',
            self::SZL => 'SZL',
            self::SSP => 'SSP',
            self::ZAR => 'ZAR',
            self::SOS => 'SOS',
            self::VND => 'VND',
            self::SGD => 'SGD',
            self::SCR => 'SCR',
            self::SAR => 'SAR',
            self::SHP => 'SHP',
            self::RWF => 'RWF',
            self::RUB => 'RUB',
            self::QAR => 'QAR',
            self::PHP => 'PHP',
            self::PEN => 'PEN',
            self::PYG => 'PYG',
            self::PGK => 'PGK',
            self::PAB => 'PAB',
            self::PKR => 'PKR',
            self::NOK => 'NOK',
            self::NGN => 'NGN',
            self::NIO => 'NIO',
            self::NZD => 'NZD',
            self::VUV => 'VUV',
            self::AWG => 'AWG',
            self::XCG => 'XCG',
            self::NPR => 'NPR',
            self::NAD => 'NAD',
            self::OMR => 'OMR',
            self::MAD => 'MAD',
            self::MDL => 'MDL',
            self::MNT => 'MNT',
            self::MXN => 'MXN',
            self::MUR => 'MUR',
            self::MVR => 'MVR',
            self::MYR => 'MYR',
            self::MWK => 'MWK',
            self::MOP => 'MOP',
            self::LYD => 'LYD',
            self::LRD => 'LRD',
            self::LSL => 'LSL',
            self::LBP => 'LBP',
            self::LAK => 'LAK',
            self::KGS => 'KGS',
            self::KWD => 'KWD',
            self::KRW => 'KRW',
            self::KPW => 'KPW',
            self::KES => 'KES',
            self::JOD => 'JOD',
            self::KZT => 'KZT',
            self::XAD => 'XAD',
            self::JPY => 'JPY',
            self::JMD => 'JMD',
            self::ILS => 'ILS',
            self::IQD => 'IQD',
            self::IRR => 'IRR',
            self::IDR => 'IDR',
            self::INR => 'INR',
            self::ISK => 'ISK',
            self::HUF => 'HUF',
            self::HKD => 'HKD',
            self::HNL => 'HNL',
            self::HTG => 'HTG',
            self::GYD => 'GYD',
            self::GNF => 'GNF',
            self::GTQ => 'GTQ',
            self::GIP => 'GIP',
            self::GMD => 'GMD',
            self::DJF => 'DJF',
            self::FJD => 'FJD',
            self::FKP => 'FKP',
            self::ERN => 'ERN',
            self::ETB => 'ETB',
            self::SVC => 'SVC',
            self::DOP => 'DOP',
            self::DKK => 'DKK',
            self::CZK => 'CZK',
            self::CUP => 'CUP',
            self::CRC => 'CRC',
            self::KMF => 'KMF',
            self::COP => 'COP',
            self::CNY => 'CNY',
            self::CLP => 'CLP',
            self::LKR => 'LKR',
            self::KYD => 'KYD',
            self::CVE => 'CVE',
            self::CAD => 'CAD',
            self::KHR => 'KHR',
            self::BIF => 'BIF',
            self::MMK => 'MMK',
            self::BND => 'BND',
            self::SBD => 'SBD',
            self::BZD => 'BZD',
            self::BWP => 'BWP',
            self::BOB => 'BOB',
            self::BTN => 'BTN',
            self::BMD => 'BMD',
            self::BBD => 'BBD',
            self::AMD => 'AMD',
            self::BDT => 'BDT',
            self::BHD => 'BHD',
            self::BSD => 'BSD',
            self::AUD => 'AUD',
            self::ARS => 'ARS',
            self::DZD => 'DZD',
            self::ALL => 'ALL',
        };
    }
}
